# Generated by Django 4.2.1 on 2023-05-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeFix', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Información del cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
