# Generated by Django 4.2.1 on 2023-05-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeFix', '0002_alter_cliente_options_alter_cliente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeFix.tipousuario'),
        ),
    ]
